[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; BT Classic (needed for the Wiimote) makes a big binary -> use a larger app partition
board_build.partitions = huge_app.csv

lib_deps =
    https://github.com/bigw00d/Arduino-ESP32Wiimote.git
    https://github.com/SolidGeek/VescUart.git
